using System.Collections.Generic;
using UnityEngine;

// Plays the game's sounds. Clips live in Assets/Resources/Audio and are
// generated by Tools/gen_audio.py. Call Sfx.Play("lamp") from anywhere.
public static class Sfx
{
    static AudioSource effects, music, ambience;
    static readonly Dictionary<string, AudioClip> clips = new();

    // Starts the music and the night ambience if they are not already going.
    public static void Begin()
    {
        if (effects != null) return;
        var go = new GameObject("Audio");
        Object.DontDestroyOnLoad(go);
        effects = go.AddComponent<AudioSource>();
        music = Loop(go, "music", 0.3f);
        ambience = Loop(go, "ambience", 0.45f);
        GameSettings.Apply();
    }

    // Both run from 0 (silent) to 1 (full).
    public static void SetVolumes(float musicLevel, float soundLevel)
    {
        if (effects == null) return;
        music.volume = 0.42f * musicLevel;
        ambience.volume = 0.55f * soundLevel;
        effects.volume = soundLevel;
    }

    static AudioSource Loop(GameObject go, string name, float volume)
    {
        var source = go.AddComponent<AudioSource>();
        source.clip = Clip(name);
        source.loop = true;
        source.volume = volume;
        source.Play();
        return source;
    }

    static AudioClip Clip(string name)
    {
        if (!clips.TryGetValue(name, out var clip))
            clips[name] = clip = Resources.Load<AudioClip>("Audio/" + name);
        return clip;
    }

    public static void Play(string name, float volume = 1f)
    {
        Begin();
        var clip = Clip(name);
        if (clip != null) effects.PlayOneShot(clip, volume);
    }

    // Quieter the further it is from what this player is looking at.
    public static void PlayAt(string name, Vector3 position, float volume = 1f)
    {
        var camera = Camera.main;
        float distance = camera != null ? Vector2.Distance(camera.transform.position, position) : 0f;
        float fade = Mathf.Clamp01(1f - (distance - 6f) / 14f);
        if (fade > 0f) Play(name, volume * fade);
    }
}
